### ISSUE TITLE
Still can't query player data...

### ISSUE THREAD

**Issue by MakiseKurisu** [leonismoe/genshin-stats#3]
#2 is closed before I can confirm the issue is fixed so here we go again.

After clicking 查询 button, an empty toast was created by [createStatStore()](https://github.com/leonismoe/genshin-stats/blob/990502a674754df87a39fff667fa4910083d87f8/packages/genshin-stats/src/store/stats.ts#L79). Tracking down the calling stack we got [`getGenshinGameStats`](https://github.com/leonismoe/genshin-stats/blob/990502a674754df87a39fff667fa4910083d87f8/packages/genshin-api/src/game-record.ts#L14)->[`request<GameStats>`](https://github.com/leonismoe/genshin-stats/blob/990502a674754df87a39fff667fa4910083d87f8/packages/api/src/utils/request-browser.ts#L114).

`console.log(response.text());` shows `{"data":null,"message":"","retcode":10103}` was received, indicating something is wrong with Mihoyo API. Tested with UID 100011111 on https://babalae.github.io/genshin-info/ to make sure UID is valid.

**Comment by leonismoe** [comment]
It seems an API request issue, unable to reproduce.
You can launch a Chromium-based browser with `--disable-web-security`, and temporarily disable Tampermonkey to find the location where the error occurred.

### Development Mode
You may clone the repository, run `npm run build:api && npm run build:genshin-data && npm run build:genshin-api` at the root of repository, then `cd packages/genshin-stats && npm run dev`.
On the development page, click the `Settings` button, then fill in the cookies and have a try.

**Comment by MakiseKurisu** [comment]
Tested again and now it is working. Not sure what happened.
